project:
  type: website
  output-dir: docs

website:
  title: Data, Code and Visualization
  description: "Notes and experiments about data, statistics, R, code, and visualization."
  site-url: https://jkunst.com/blog
  repo-url: https://github.com/jbkunst/blog
  repo-actions: [source, issue]
  open-graph: true
  twitter-card: true
  back-to-top-navigation: true

  navbar:
    tools:
      - icon: info-circle
        aria-label: About
        href: about.qmd
      - icon: github
        aria-label: GitHub
        href: https://github.com/jbkunst/blog
  page-footer:
    left: "© Joshua Kunst"
    right: "Made with Quarto, open source, and ☕"

format:
  html:
    theme: materia
    css: styles.css
    code-copy: hover
    code-overflow: wrap
    code-tools: false
    code-block-border-left: true
    code-link: true
    code-fold: show
    smooth-scroll: true
